version: 2
updates:
  # GitHub Actions - monthly updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"

  # Fairy-Stockfish related npm packages - weekly updates
  - package-ecosystem: "npm"
    target-branch: "main" # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "fairy-stockfish-nnue.wasm"
      - dependency-name: "ffish-es6"
    groups:
      fairy-stockfish:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "npm"
      - "fairy-stockfish"

  # All other npm packages - monthly updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "fairy-stockfish-nnue.wasm"
      - dependency-name: "ffish-es6"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "npm"



